### PR TITLE
User Profile attrib profile added

### PR DESCRIPTION
**Pull request by JDFleury**
Forgot to add the attribute to User Profile called profile that lets us determine the two possible profiles available: conchyliculteur or autres

### CODE REVIEW

**Review by bobeal — COMMENTED** [review]
did not pay attention in the 1st PR but the sample should be renamed to `userProfile.jsonld` (orally transmitted naming convention...).

**Comment by bobeal** [comment]
> did not pay attention in the 1st PR but the sample should be renamed to `userProfile.jsonld` (orally transmitted naming convention...).

well, forget about this, existing payloads do not follow the convention...

**Review by bobeal — APPROVED** [review]

**Comment by junjou** [comment]
> did not pay attention in the 1st PR but the sample should be renamed to `userProfile.jsonld` (orally transmitted naming convention...).

I agree and it's not too late to try to apply our orally transmitted naming convention. Which is IIRC `camelCase` for files and `kebab-case` for directories. But IMO we should simplify even more and do camelCase all the time.

**Review by junjou — APPROVED** [review]
OK

**Pull request merged**
